name: pub_unscripted_example
version: 0.0.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Example of how to implement pub with unscripted.
homepage: http://github.com/seaneagan/pub_unscripted_example
dependencies:
  unscripted: '>=0.5.0 <0.6.0'
executables:
  pub_unscripted:
